services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - polls_pg_data:/var/lib/postgresql/data
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  polls_pg_data:
